### ISSUE TITLE
⛰️[EPIC]: VFGN Integration

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#335]
Tracker for the issues related to integrating VFGN

```[tasklist]
### Pytest
- [ ] https://github.com/NVIDIA/modulus/issues/451
```

**Comment by jl626** [comment]
![current_errors](https://github.com/NVIDIA/modulus/assets/34041349/d7937d5f-2c93-4981-bec5-d561f17cba67)

Excluding entry point one, there are 3 more errors. 

1. Checkpointing is not compatible with .grad() or when an `inputs` parameter is passed to .backward(). 

This one is because our code includes torch.util.checkpoint function, which does not support torch.grad. It only supports backward()

2.   RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

This is mainy because VFGN have multiple inputs including scalar integers. 

3. TypeError: Object of type Tensor is not JSON serializable

I have no idea what causing this error.

**Comment by dearleiii** [comment]
TypeError: Object of type Tensor is not JSON serializable

seems  in checkpooints.py
save function does not take type TorchTensor or a predefined class as input,  class LearnedSimulator() initialization does create these tensors in arg "boundaries" and "normalization_stats"


   # First check fail safes of save/load functions
    try:
        model_1.save("folder_does_not_exist/checkpoint.mdlus")
    except IOError:
        pass
